on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            .venv/
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Copy PyInstaller Dependencies
        shell: pwsh
        run: |
          # Ensure the directory for DLLs exists
          mkdir pyzbar

          # Locate the Python site-packages directory
          $site_packages = "C:\hostedtoolcache\windows\Python\3.12.3\x64\Lib\site-packages"

          # Copy DLLs from site-packages directory to pyzbar folder
          Copy-Item -Path "$site_packages\pyzbar\libiconv.dll" -Destination "pyzbar\" -Force
          Copy-Item -Path "$site_packages\pyzbar\libzbar-64.dll" -Destination "pyzbar\" -Force

      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12.3'
          spec: 'QRCode.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'QRexe'
          options: --onefile --name "My App" --windowed
